name: Arbitrage Automation

on:
  workflow_dispatch:
  schedule:
    # Optional: Run every 6 hours
    # - cron: '0 */6 * * *'

jobs:
  run-arbitrage:
    runs-on: ubuntu-latest
    timeout-minutes: 120  # Set timeout to 2 hours

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          playwright install
          playwright install-deps

      - name: Run main script
        run: python run.py
        env:
          # Add any environment variables your scripts need
          PYTHONUNBUFFERED: "1"

      - name: Upload logs (if any)
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: arbitrage-logs
          path: |
            *.log
            *.txt
          retention-days: 7